### PR TITLE
Fix version # for go tools

### PR DESCRIPTION
**Pull request by mattdot**
This pull request includes a minor change to the `go.mod` file. The Go version has been updated from `1.21` to `1.21.9`, ensuring that the project uses the latest patch release of Go 1.21.

### CODE REVIEW

**Comment by mattdot** [comment]
Looks like tfproviderlint is using an old version of go in their dockerfile.  Need to figure out how to run with the new spec.

**Review by polatengin — DISMISSED** [review]
lgtm 👍

**Comment by eduardodfmex** [comment]
This fix is covered on the PR 284: https://github.com/microsoft/terraform-provider-power-platform/pull/284

**Review by eduardodfmex — COMMENTED** [review]
This fix is covered on the PR 284: https://github.com/microsoft/terraform-provider-power-platform/pull/284

**Pull request closed without merging**
