### PR TITLE
Fix proposition for the inversion between "Business" and "Non-business" connectors groups in Power Platform DLP policies

### PR DESCRIPTION
**Pull request by rpothin**
## Related issue(s)

- #288 

## Overview of the changed files

- Code
   - datasource_dlp_policy.go
   - resource_dlp_policy.go
- Unit tests
   - datasource_dlp_policy_test.go
   - resource_dlp_policy_test.go

## Validation

The latest execution of the [Terraform Provider Checks](https://github.com/rpothin/terraform-provider-power-platform/actions/runs/9019799110) workflow in my repository (_fork_) after the implementation of the changes in this pull request has been successful.

> [!NOTE]
> Don't hesitate to ping me in the comment if you have questions or requests regarding this pull request.

> [!NOTE]
> I am sorry, I did not take the time to implement brand new acceptance tests for the Power Platform DLP scope. I thought correcting this bug quickly was more important. It could definitely be part of future improvement work.

### CODE REVIEW

**Review by mawasile — APPROVED** [review]

**Comment by mawasile** [comment]
Thanks for contribution, looks ok. I will add the missing acceptance test

**Review by mattdot — APPROVED** [review]
@rpothin  thanks for your contribution

**Comment by rpothin** [comment]
Hi team 👋🏼,

Thank you @mawasile and @mattdot for the review and the approval.

I am really interested in your work on this provider and I think I will try to contribute more in the future if you are open to this idea.

I already started a repository under my personal account to try to evangelize and showcase the provider to the Power Platform community: [rpothin/PowerPlatform-Governance-With-Terraform](https://github.com/rpothin/PowerPlatform-Governance-With-Terraform)

Have a great day.

**Comment by mawasile** [comment]
Hi @rpothin 

Your welcome to contribute. I've seen your repo and it looks interesting. If you will have any questions or blocker you can reach us via email/msteams over github or on @microsoft (our mail aliases are the same as our github user names, or firstname.lastname)

**Comment by mattdot** [comment]
We are definitely open to it. Let us know what resources or data sources would help your use cases maybe we could start there.

We're interested to see where your governance work goes.  Definitely a scenario that we want to enable with the provider.

We'll probably create a new release that includes your PR in a couple days once the data record pr also merges.

**Pull request merged**
